name: nophonechallenge # <--- BELANGRIJK: ZORG DAT DIT OVEREENKOMT MET JE EIGEN PROJECTNAAM!
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  fl_chart: ^0.68.0

  bloc_presentation: ^1.1.1
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  device_info_plus: ^10.0.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  permission_handler: ^11.1.0
  intl: ^0.19.0
  get_it: ^7.6.0
  flutter_native_splash: ^2.4.0
  equatable: ^2.0.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Om een logo in de QR code te hebben (maak de map 'assets' aan en plaats je logo daarin)
  assets:
      - assets/app_logo.png
